In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
import numpy as np
import pandas as pd 

import tqdm
from pathlib import Path
from collections import defaultdict, Counter

In [3]:
DATA_ROOT = Path('../input/kakr-3rd-copy/')
train_csv = pd.read_csv('../input/kakr-3rd-copy/train.csv')

In [24]:
def make_folds(n_folds: int) -> pd.DataFrame:
    df = pd.read_csv(DATA_ROOT / 'train.csv', engine='python')

    cls_counts = Counter([classes for classes in df['class']])
    fold_cls_counts = defaultdict()
    
    for class_index in cls_counts.keys():
        fold_cls_counts[class_index] = np.zeros(n_folds, dtype=np.int)   
        
    df['fold'] = -1    
    pbar = tqdm.tqdm(total=len(df))

    def get_fold(row):
        class_index = row['class']
        counts = fold_cls_counts[class_index]
        
        fold = np.argmin(counts)
        counts[fold] += 1
        fold_cls_counts[class_index] = counts
        row['fold']=fold
        
        pbar.update()
        return row
        
    df = df.apply(get_fold, axis=1)
    return df

In [25]:
df = make_folds(n_folds=5)
print("df:")
print(df)
df.to_csv('folds2.csv', index=None)



  0%|          | 0/9990 [00:00<?, ?it/s]

  3%|▎         | 299/9990 [00:00<00:03, 2988.36it/s]

fold_cls_counts
defaultdict(None, {108: array([0, 0, 0, 0, 0]), 71: array([0, 0, 0, 0, 0]), 76: array([0, 0, 0, 0, 0]), 188: array([0, 0, 0, 0, 0]), 44: array([0, 0, 0, 0, 0]), 29: array([0, 0, 0, 0, 0]), 113: array([0, 0, 0, 0, 0]), 66: array([0, 0, 0, 0, 0]), 97: array([0, 0, 0, 0, 0]), 177: array([0, 0, 0, 0, 0]), 142: array([0, 0, 0, 0, 0]), 10: array([0, 0, 0, 0, 0]), 127: array([0, 0, 0, 0, 0]), 64: array([0, 0, 0, 0, 0]), 93: array([0, 0, 0, 0, 0]), 39: array([0, 0, 0, 0, 0]), 196: array([0, 0, 0, 0, 0]), 173: array([0, 0, 0, 0, 0]), 135: array([0, 0, 0, 0, 0]), 152: array([0, 0, 0, 0, 0]), 178: array([0, 0, 0, 0, 0]), 134: array([0, 0, 0, 0, 0]), 131: array([0, 0, 0, 0, 0]), 50: array([0, 0, 0, 0, 0]), 28: array([0, 0, 0, 0, 0]), 65: array([0, 0, 0, 0, 0]), 21: array([0, 0, 0, 0, 0]), 30: array([0, 0, 0, 0, 0]), 91: array([0, 0, 0, 0, 0]), 164: array([0, 0, 0, 0, 0]), 4: array([0, 0, 0, 0, 0]), 5: array([0, 0, 0, 0, 0]), 180: array([0, 0, 0, 0, 0]), 193: array([0, 0, 0, 0, 0]),



  5%|▌         | 545/9990 [00:00<00:03, 2806.55it/s]

  7%|▋         | 743/9990 [00:00<00:03, 2492.64it/s]

counts
[1 0 0 0 0]
counts
[2 1 1 1 1]
counts
[1 1 1 0 0]
counts
[1 1 1 1 1]
counts
[1 1 1 1 1]
counts
[1 0 0 0 0]
counts
[1 1 0 0 0]
counts
[1 1 1 0 0]
counts
[1 1 1 0 0]
counts
[1 1 0 0 0]
counts
[1 1 1 0 0]
counts
[1 1 1 1 0]
counts
[1 1 0 0 0]
counts
[1 1 0 0 0]
counts
[0 0 0 0 0]
counts
[1 1 0 0 0]
counts
[1 1 0 0 0]
counts
[1 1 0 0 0]
counts
[1 1 0 0 0]
counts
[1 0 0 0 0]
counts
[2 1 1 1 1]
counts
[1 1 0 0 0]
counts
[0 0 0 0 0]
counts
[1 1 0 0 0]
counts
[1 0 0 0 0]
counts
[1 1 0 0 0]
counts
[1 1 0 0 0]
counts
[1 1 1 1 0]
counts
[1 1 1 1 1]
counts
[1 0 0 0 0]
counts
[1 1 1 1 1]
counts
[1 1 1 0 0]
counts
[1 1 0 0 0]
counts
[1 0 0 0 0]
counts
[1 1 0 0 0]
counts
[1 1 0 0 0]
counts
[1 1 1 0 0]
counts
[1 1 1 1 1]
counts
[1 1 0 0 0]
counts
[1 1 1 0 0]
counts
[1 1 0 0 0]
counts
[1 1 0 0 0]
counts
[1 1 1 0 0]
counts
[2 2 1 1 1]
counts
[1 1 1 1 0]
counts
[1 1 1 0 0]
counts
[1 1 0 0 0]
counts
[1 1 0 0 0]
counts
[1 1 1 1 1]
counts
[1 1 0 0 0]
counts
[1 1 1 1 0]
counts
[1 1 0 0 0]
counts
[1 1 



  9%|▉         | 924/9990 [00:00<00:04, 2237.18it/s]

 11%|█         | 1109/9990 [00:00<00:04, 2104.07it/s]

counts
[1 1 1 0 0]
counts
[1 1 1 0 0]
counts
[1 1 0 0 0]
counts
[2 1 1 1 1]
counts
[1 1 1 1 1]
counts
[1 1 1 1 1]
counts
[1 1 1 0 0]
counts
[1 1 1 1 1]
counts
[1 1 1 1 1]
counts
[1 1 0 0 0]
counts
[1 1 1 0 0]
counts
[1 1 1 1 0]
counts
[1 1 0 0 0]
counts
[2 1 1 1 1]
counts
[1 1 1 1 0]
counts
[1 1 0 0 0]
counts
[2 2 2 1 1]
counts
[2 1 1 1 1]
counts
[2 2 2 2 1]
counts
[1 1 1 1 1]
counts
[1 1 1 0 0]
counts
[1 1 1 1 0]
counts
[1 1 1 1 1]
counts
[1 1 1 1 0]
counts
[1 1 1 1 0]
counts
[1 1 0 0 0]
counts
[1 1 1 1 1]
counts
[1 1 0 0 0]
counts
[1 1 0 0 0]
counts
[1 1 1 1 0]
counts
[2 1 1 1 1]
counts
[1 1 1 1 0]
counts
[1 1 0 0 0]
counts
[2 2 1 1 1]
counts
[1 1 1 1 0]
counts
[1 1 1 1 1]
counts
[1 1 1 1 0]
counts
[1 1 1 0 0]
counts
[2 2 1 1 1]
counts
[2 2 2 1 1]
counts
[1 1 1 1 1]
counts
[1 1 1 1 0]
counts
[1 1 1 1 0]
counts
[1 1 1 1 0]
counts
[1 1 1 1 1]
counts
[1 1 1 1 1]
counts
[2 2 1 1 1]
counts
[1 1 1 0 0]
counts
[1 0 0 0 0]
counts
[1 1 0 0 0]
counts
[1 1 1 1 1]
counts
[1 1 1 1 0]
counts
[1 1 



 13%|█▎        | 1336/9990 [00:00<00:04, 2078.61it/s]

 15%|█▌        | 1544/9990 [00:00<00:04, 2068.67it/s]


[1 1 1 1 1]
counts
[3 3 2 2 2]
counts
[1 1 1 1 1]
counts
[2 2 1 1 1]
counts
[2 1 1 1 1]
counts
[2 2 2 1 1]
counts
[2 2 2 1 1]
counts
[2 2 2 1 1]
counts
[2 2 2 2 2]
counts
[2 2 1 1 1]
counts
[3 2 2 2 2]
counts
[2 2 2 1 1]
counts
[1 1 1 1 1]
counts
[2 1 1 1 1]
counts
[2 2 2 1 1]
counts
[3 2 2 2 2]
counts
[2 1 1 1 1]
counts
[2 2 2 1 1]
counts
[2 2 1 1 1]
counts
[2 2 2 2 1]
counts
[2 2 1 1 1]
counts
[2 1 1 1 1]
counts
[2 2 2 1 1]
counts
[1 1 1 0 0]
counts
[2 2 2 2 1]
counts
[1 1 1 0 0]
counts
[2 2 2 1 1]
counts
[1 1 1 1 1]
counts
[1 1 1 0 0]
counts
[2 2 2 1 1]
counts
[2 1 1 1 1]
counts
[1 1 1 1 0]
counts
[2 2 2 2 2]
counts
[3 2 2 2 2]
counts
[2 1 1 1 1]
counts
[2 2 2 2 2]
counts
[1 1 0 0 0]
counts
[2 2 1 1 1]
counts
[1 1 1 1 0]
counts
[3 2 2 2 2]
counts
[1 1 1 0 0]
counts
[2 1 1 1 1]
counts
[2 2 2 2 2]
counts
[2 2 1 1 1]
counts
[2 2 1 1 1]
counts
[2 2 1 1 1]
counts
[2 1 1 1 1]
counts
[1 1 1 1 1]
counts
[2 2 2 1 1]
counts
[2 2 2 2 1]
counts
[2 2 1 1 1]
counts
[1 1 1 1 1]
counts
[2 2 2 2 2]



 17%|█▋        | 1731/9990 [00:00<00:04, 1986.48it/s]

 19%|█▉        | 1919/9990 [00:00<00:04, 1952.90it/s]

counts
[2 2 2 2 2]
counts
[2 2 2 1 1]
counts
[2 2 2 1 1]
counts
[2 2 2 2 1]
counts
[1 1 1 1 1]
counts
[2 1 1 1 1]
counts
[3 2 2 2 2]
counts
[2 2 2 2 2]
counts
[3 2 2 2 2]
counts
[2 2 2 2 2]
counts
[2 2 1 1 1]
counts
[2 2 2 2 2]
counts
[2 2 1 1 1]
counts
[2 2 2 2 1]
counts
[3 2 2 2 2]
counts
[2 1 1 1 1]
counts
[2 2 1 1 1]
counts
[1 1 1 1 1]
counts
[2 2 2 1 1]
counts
[2 2 2 1 1]
counts
[2 2 2 1 1]
counts
[3 2 2 2 2]
counts
[2 2 2 2 1]
counts
[3 2 2 2 2]
counts
[2 2 2 1 1]
counts
[3 2 2 2 2]
counts
[2 2 2 1 1]
counts
[1 1 1 1 1]
counts
[2 2 2 2 2]
counts
[2 2 2 2 2]
counts
[2 2 2 2 2]
counts
[2 2 1 1 1]
counts
[2 2 2 1 1]
counts
[2 2 1 1 1]
counts
[2 2 1 1 1]
counts
[1 1 1 1 1]
counts
[2 2 2 2 1]
counts
[2 2 1 1 1]
counts
[4 3 3 3 3]
counts
[2 2 2 2 2]
counts
[2 2 1 1 1]
counts
[2 2 2 2 2]
counts
[2 2 2 2 1]
counts
[3 3 3 3 2]
counts
[2 2 2 1 1]
counts
[1 1 1 1 1]
counts
[1 1 1 1 1]
counts
[2 2 1 1 1]
counts
[3 3 2 2 2]
counts
[2 2 2 2 2]
counts
[2 2 2 1 1]
counts
[2 2 2 1 1]
counts
[2 2 



 21%|██        | 2106/9990 [00:01<00:04, 1815.02it/s]

 23%|██▎       | 2296/9990 [00:01<00:04, 1838.35it/s]


counts
[4 4 4 4 4]
counts
[2 2 1 1 1]
counts
[2 1 1 1 1]
counts
[2 1 1 1 1]
counts
[3 3 3 3 2]
counts
[4 3 3 3 3]
counts
[4 3 3 3 3]
counts
[2 2 2 1 1]
counts
[2 2 2 2 2]
counts
[2 2 2 2 2]
counts
[2 2 2 1 1]
counts
[3 3 3 3 3]
counts
[2 1 1 1 1]
counts
[2 2 2 2 1]
counts
[3 2 2 2 2]
counts
[3 3 3 3 2]
counts
[2 2 2 2 1]
counts
[2 1 1 1 1]
counts
[2 2 2 1 1]
counts
[3 3 3 3 3]
counts
[4 4 3 3 3]
counts
[3 3 3 3 3]
counts
[3 3 3 2 2]
counts
[2 2 2 2 1]
counts
[3 3 3 2 2]
counts
[3 3 3 3 2]
counts
[2 2 1 1 1]
counts
[2 2 2 2 2]
counts
[3 3 3 2 2]
counts
[3 3 3 2 2]
counts
[2 2 2 2 2]
counts
[2 2 2 2 1]
counts
[3 3 3 3 2]
counts
[2 2 2 2 2]
counts
[3 3 2 2 2]
counts
[2 2 2 2 1]
counts
[3 2 2 2 2]
counts
[2 2 2 2 2]
counts
[3 3 3 2 2]
counts
[2 2 2 1 1]
counts
[2 2 2 1 1]
counts
[4 3 3 3 3]
counts
[3 3 3 2 2]
counts
[2 2 2 1 1]
counts
[3 3 3 3 3]
counts
[2 2 1 1 1]
counts
[3 3 3 3 2]
counts
[2 2 2 2 1]
counts
[3 2 2 2 2]
counts
[2 2 2 1 1]
counts
[4 4 4 3 3]
counts
[2 2 2 2 2]
counts
[3 3



 25%|██▍       | 2479/9990 [00:01<00:04, 1827.66it/s]

 27%|██▋       | 2677/9990 [00:01<00:03, 1867.94it/s]

counts
[2 2 2 2 1]
counts
[3 3 3 3 3]
counts
[3 3 3 2 2]
counts
[3 3 3 2 2]
counts
[2 2 2 2 2]
counts
[2 2 2 2 1]
counts
[3 3 3 2 2]
counts
[4 3 3 3 3]
counts
[2 2 1 1 1]
counts
[3 3 2 2 2]
counts
[3 3 3 3 2]
counts
[2 2 2 1 1]
counts
[3 3 3 3 2]
counts
[4 4 3 3 3]
counts
[3 3 3 2 2]
counts
[3 3 3 3 3]
counts
[3 2 2 2 2]
counts
[2 2 2 2 2]
counts
[3 3 3 2 2]
counts
[3 3 2 2 2]
counts
[3 3 3 3 3]
counts
[3 3 3 3 2]
counts
[2 2 2 2 1]
counts
[4 3 3 3 3]
counts
[2 1 1 1 1]
counts
[3 3 3 2 2]
counts
[3 3 3 2 2]
counts
[3 3 3 3 2]
counts
[3 3 2 2 2]
counts
[3 3 3 3 2]
counts
[3 3 3 3 2]
counts
[3 3 3 2 2]
counts
[2 2 2 2 2]
counts
[3 2 2 2 2]
counts
[2 2 2 1 1]
counts
[3 3 2 2 2]
counts
[3 3 2 2 2]
counts
[3 3 3 3 3]
counts
[2 2 2 1 1]
counts
[3 3 3 3 2]
counts
[3 3 3 2 2]
counts
[2 2 1 1 1]
counts
[2 2 2 1 1]
counts
[3 3 3 2 2]
counts
[4 3 3 3 3]
counts
[2 2 1 1 1]
counts
[3 3 2 2 2]
counts
[2 2 1 1 1]
counts
[4 3 3 3 3]
counts
[2 1 1 1 1]
counts
[2 2 2 2 2]
counts
[4 4 4 3 3]
counts
[2 2 



 29%|██▊       | 2868/9990 [00:01<00:03, 1879.87it/s]

 31%|███       | 3067/9990 [00:01<00:03, 1907.67it/s]



[3 2 2 2 2]
counts
[4 3 3 3 3]
counts
[3 3 2 2 2]
counts
[3 2 2 2 2]
counts
[3 3 2 2 2]
counts
[2 2 2 2 1]
counts
[3 3 3 3 2]
counts
[3 3 3 3 3]
counts
[4 4 4 3 3]
counts
[3 3 3 3 2]
counts
[3 3 3 2 2]
counts
[4 4 4 4 4]
counts
[4 4 3 3 3]
counts
[3 3 2 2 2]
counts
[4 3 3 3 3]
counts
[3 3 3 3 2]
counts
[5 5 4 4 4]
counts
[4 4 3 3 3]
counts
[3 3 3 3 2]
counts
[2 2 2 2 2]
counts
[5 5 5 5 5]
counts
[2 2 2 1 1]
counts
[4 4 4 4 4]
counts
[3 3 3 3 2]
counts
[3 3 2 2 2]
counts
[4 4 3 3 3]
counts
[3 3 3 3 2]
counts
[3 3 3 3 3]
counts
[2 2 2 2 2]
counts
[4 4 4 4 3]
counts
[5 4 4 4 4]
counts
[3 2 2 2 2]
counts
[4 3 3 3 3]
counts
[3 3 3 3 3]
counts
[3 3 3 3 3]
counts
[4 3 3 3 3]
counts
[4 4 4 3 3]
counts
[4 4 4 4 3]
counts
[3 2 2 2 2]
counts
[4 4 4 4 3]
counts
[4 4 4 4 4]
counts
[3 3 3 3 3]
counts
[4 4 4 4 3]
counts
[5 4 4 4 4]
counts
[4 4 3 3 3]
counts
[3 3 2 2 2]
counts
[4 4 3 3 3]
counts
[3 3 2 2 2]
counts
[4 4 4 4 3]
counts
[3 3 3 3 2]
counts
[4 4 4 3 3]
counts
[4 4 4 4 4]
counts
[3 3 2 2 2]


 33%|███▎      | 3277/9990 [00:01<00:03, 1960.20it/s]

 35%|███▍      | 3487/9990 [00:01<00:03, 1998.62it/s]

 37%|███▋      | 3688/9990 [00:01<00:03, 1979.36it/s]

counts
[4 3 3 3 3]
counts
[2 2 2 2 1]
counts
[4 4 4 4 4]
counts
[3 3 3 3 2]
counts
[5 4 4 4 4]
counts
[4 4 3 3 3]
counts
[4 4 4 3 3]
counts
[5 5 5 4 4]
counts
[5 5 5 4 4]
counts
[5 5 5 5 4]
counts
[4 3 3 3 3]
counts
[4 4 4 3 3]
counts
[5 5 5 5 5]
counts
[3 2 2 2 2]
counts
[5 5 4 4 4]
counts
[4 4 4 4 3]
counts
[5 4 4 4 4]
counts
[5 5 4 4 4]
counts
[4 4 4 3 3]
counts
[5 5 4 4 4]
counts
[3 3 3 3 2]
counts
[4 4 4 4 4]
counts
[5 4 4 4 4]
counts
[3 3 2 2 2]
counts
[4 3 3 3 3]
counts
[2 2 2 2 1]
counts
[2 2 2 2 1]
counts
[3 3 3 2 2]
counts
[3 2 2 2 2]
counts
[3 3 3 3 3]
counts
[3 3 3 3 3]
counts
[4 3 3 3 3]
counts
[3 3 2 2 2]
counts
[4 4 3 3 3]
counts
[4 4 4 4 3]
counts
[3 3 3 3 3]
counts
[4 4 4 3 3]
counts
[4 4 4 4 3]
counts
[4 4 4 4 3]
counts
[5 5 5 4 4]
counts
[2 2 2 2 1]
counts
[3 3 3 3 2]
counts
[3 3 3 2 2]
counts
[5 5 4 4 4]
counts
[4 4 3 3 3]
counts
[4 3 3 3 3]
counts
[3 3 3 3 3]
counts
[3 3 3 3 2]
counts
[3 3 3 3 2]
counts
[3 3 3 3 2]
counts
[5 5 5 5 4]
counts
[3 3 2 2 2]
counts
[2 2 



 39%|███▉      | 3887/9990 [00:01<00:03, 1884.01it/s]

 41%|████      | 4078/9990 [00:02<00:03, 1891.42it/s]

counts
[3 3 3 3 2]
counts
[4 4 3 3 3]
counts
[5 4 4 4 4]
counts
[4 4 4 4 3]
counts
[4 4 4 4 4]
counts
[4 4 4 3 3]
counts
[4 4 4 4 4]
counts
[5 5 5 5 4]
counts
[3 3 3 2 2]
counts
[3 3 3 2 2]
counts
[3 3 3 3 2]
counts
[4 4 3 3 3]
counts
[4 4 3 3 3]
counts
[4 4 4 4 4]
counts
[4 4 4 4 4]
counts
[5 5 5 4 4]
counts
[6 5 5 5 5]
counts
[3 3 3 2 2]
counts
[4 4 4 4 4]
counts
[4 4 4 4 4]
counts
[5 5 4 4 4]
counts
[3 3 3 3 3]
counts
[5 5 5 4 4]
counts
[4 4 4 3 3]
counts
[4 4 3 3 3]
counts
[5 5 4 4 4]
counts
[3 3 3 3 2]
counts
[3 3 3 3 2]
counts
[4 4 3 3 3]
counts
[4 4 3 3 3]
counts
[6 5 5 5 5]
counts
[6 6 6 5 5]
counts
[4 4 4 4 4]
counts
[4 4 4 3 3]
counts
[4 4 4 4 3]
counts
[4 4 4 4 3]
counts
[3 3 3 3 2]
counts
[4 4 4 4 4]
counts
[5 4 4 4 4]
counts
[4 4 4 3 3]
counts
[4 4 4 4 4]
counts
[4 4 4 4 3]
counts
[5 4 4 4 4]
counts
[4 4 3 3 3]
counts
[3 3 3 3 2]
counts
[4 4 4 4 4]
counts
[4 4 4 4 3]
counts
[4 4 4 4 3]
counts
[4 4 4 4 3]
counts
[4 4 4 4 3]
counts
[4 4 4 4 4]
counts
[5 5 5 4 4]
counts
[5 5 



 43%|████▎     | 4289/9990 [00:02<00:02, 1909.87it/s]

 45%|████▍     | 4490/9990 [00:02<00:02, 1937.96it/s]

counts
[6 5 5 5 5]
counts
[5 5 4 4 4]
counts
[5 5 4 4 4]
counts
[4 4 4 3 3]
counts
[6 6 6 6 5]
counts
[5 5 5 4 4]
counts
[4 4 4 3 3]
counts
[5 5 5 4 4]
counts
[4 3 3 3 3]
counts
[4 3 3 3 3]
counts
[4 4 4 4 4]
counts
[4 3 3 3 3]
counts
[5 5 5 4 4]
counts
[5 5 4 4 4]
counts
[5 5 5 4 4]
counts
[4 4 4 4 3]
counts
[4 4 4 4 3]
counts
[6 6 6 6 6]
counts
[5 4 4 4 4]
counts
[6 6 6 5 5]
counts
[5 5 5 4 4]
counts
[3 3 3 2 2]
counts
[4 4 4 4 4]
counts
[6 5 5 5 5]
counts
[5 5 5 4 4]
counts
[6 6 5 5 5]
counts
[6 6 5 5 5]
counts
[5 5 4 4 4]
counts
[6 6 6 5 5]
counts
[3 3 2 2 2]
counts
[5 5 5 4 4]
counts
[3 3 3 3 2]
counts
[4 4 4 3 3]
counts
[5 4 4 4 4]
counts
[5 5 5 5 4]
counts
[4 4 3 3 3]
counts
[6 6 6 5 5]
counts
[3 3 3 3 2]
counts
[5 4 4 4 4]
counts
[4 4 4 4 4]
counts
[5 5 5 5 5]
counts
[5 5 5 5 5]
counts
[5 5 5 5 4]
counts
[4 3 3 3 3]
counts
[5 4 4 4 4]
counts
[5 5 5 5 4]
counts
[5 5 4 4 4]
counts
[4 4 4 4 4]
counts
[4 4 3 3 3]
counts
[5 4 4 4 4]
counts
[6 5 5 5 5]
counts
[5 5 5 5 4]
counts
[5 5 



 47%|████▋     | 4685/9990 [00:02<00:02, 1865.24it/s]

 49%|████▉     | 4877/9990 [00:02<00:02, 1880.26it/s]


[4 4 3 3 3]
counts
[5 5 5 4 4]
counts
[7 6 6 6 6]
counts
[4 4 4 3 3]
counts
[5 5 5 4 4]
counts
[5 5 5 4 4]
counts
[5 4 4 4 4]
counts
[5 5 5 4 4]
counts
[6 6 6 6 5]
counts
[4 4 4 4 4]
counts
[6 6 6 5 5]
counts
[6 6 6 6 5]
counts
[5 5 4 4 4]
counts
[5 5 5 5 5]
counts
[4 4 4 3 3]
counts
[4 4 4 4 4]
counts
[6 5 5 5 5]
counts
[3 3 3 2 2]
counts
[5 4 4 4 4]
counts
[4 4 4 4 4]
counts
[5 5 5 5 4]
counts
[6 5 5 5 5]
counts
[6 6 5 5 5]
counts
[5 5 5 5 4]
counts
[8 8 8 7 7]
counts
[6 6 6 6 5]
counts
[7 7 6 6 6]
counts
[5 5 5 5 5]
counts
[4 3 3 3 3]
counts
[5 5 5 4 4]
counts
[4 4 4 4 4]
counts
[6 6 6 5 5]
counts
[5 5 5 5 5]
counts
[5 4 4 4 4]
counts
[5 4 4 4 4]
counts
[6 5 5 5 5]
counts
[5 5 4 4 4]
counts
[5 5 4 4 4]
counts
[5 5 5 4 4]
counts
[6 6 6 6 5]
counts
[4 4 3 3 3]
counts
[5 5 5 5 4]
counts
[5 5 4 4 4]
counts
[6 6 6 6 6]
counts
[3 3 3 2 2]
counts
[5 5 5 5 5]
counts
[5 4 4 4 4]
counts
[6 6 5 5 5]
counts
[6 6 6 5 5]
counts
[3 3 3 2 2]
counts
[4 4 4 4 3]
counts
[6 6 6 5 5]
counts
[5 4 4 4 4]



 51%|█████     | 5091/9990 [00:02<00:02, 1950.30it/s]

 53%|█████▎    | 5288/9990 [00:02<00:02, 1934.48it/s]

counts
[6 6 5 5 5]
counts
[6 6 5 5 5]
counts
[5 5 4 4 4]
counts
[5 5 5 5 4]
counts
[5 5 5 4 4]
counts
[5 5 4 4 4]
counts
[5 4 4 4 4]
counts
[6 6 6 6 6]
counts
[7 7 6 6 6]
counts
[4 4 4 4 4]
counts
[5 5 5 5 5]
counts
[6 5 5 5 5]
counts
[5 5 5 5 4]
counts
[6 5 5 5 5]
counts
[5 5 5 5 5]
counts
[7 7 6 6 6]
counts
[6 6 6 5 5]
counts
[4 4 4 4 3]
counts
[6 6 6 5 5]
counts
[6 6 5 5 5]
counts
[6 6 6 5 5]
counts
[5 5 5 4 4]
counts
[6 6 6 6 5]
counts
[6 6 6 5 5]
counts
[5 5 5 5 5]
counts
[5 5 5 5 4]
counts
[5 5 5 4 4]
counts
[5 5 5 5 5]
counts
[5 5 5 5 4]
counts
[7 6 6 6 6]
counts
[6 5 5 5 5]
counts
[7 7 7 6 6]
counts
[5 4 4 4 4]
counts
[6 5 5 5 5]
counts
[5 5 5 4 4]
counts
[5 5 5 5 5]
counts
[4 4 4 4 4]
counts
[6 5 5 5 5]
counts
[7 7 7 7 6]
counts
[5 5 5 5 4]
counts
[6 6 6 6 5]
counts
[4 4 4 4 4]
counts
[5 5 4 4 4]
counts
[4 4 3 3 3]
counts
[6 6 5 5 5]
counts
[5 5 5 5 4]
counts
[4 4 4 4 4]
counts
[5 5 5 5 5]
counts
[9 8 8 8 8]
counts
[6 5 5 5 5]
counts
[5 5 5 5 5]
counts
[5 5 5 5 5]
counts
[7 6 



 55%|█████▍    | 5483/9990 [00:02<00:02, 1904.23it/s]

 57%|█████▋    | 5675/9990 [00:02<00:02, 1863.00it/s]

counts
[6 5 5 5 5]
counts
[6 6 6 6 5]
counts
[5 5 5 5 4]
counts
[7 6 6 6 6]
counts
[6 6 6 5 5]
counts
[5 5 5 5 5]
counts
[5 4 4 4 4]
counts
[7 7 6 6 6]
counts
[5 5 5 5 4]
counts
[6 6 6 5 5]
counts
[6 6 6 6 6]
counts
[6 5 5 5 5]
counts
[5 5 4 4 4]
counts
[7 6 6 6 6]
counts
[7 7 6 6 6]
counts
[5 5 5 5 5]
counts
[5 5 4 4 4]
counts
[6 6 6 6 5]
counts
[6 6 6 6 5]
counts
[4 4 4 4 4]
counts
[7 7 6 6 6]
counts
[5 5 5 5 5]
counts
[7 6 6 6 6]
counts
[5 5 5 5 5]
counts
[4 3 3 3 3]
counts
[4 4 4 4 4]
counts
[6 6 6 6 6]
counts
[5 5 5 5 4]
counts
[6 5 5 5 5]
counts
[5 5 5 5 4]
counts
[6 6 6 6 6]
counts
[5 5 4 4 4]
counts
[5 5 5 4 4]
counts
[6 6 5 5 5]
counts
[5 5 5 5 5]
counts
[6 6 6 6 6]
counts
[5 5 5 5 5]
counts
[5 4 4 4 4]
counts
[5 4 4 4 4]
counts
[6 5 5 5 5]
counts
[7 6 6 6 6]
counts
[5 5 5 5 4]
counts
[7 7 7 7 7]
counts
[6 6 5 5 5]
counts
[6 6 5 5 5]
counts
[5 5 5 5 5]
counts
[7 7 6 6 6]
counts
[5 5 5 5 5]
counts
[5 5 5 5 4]
counts
[5 4 4 4 4]
counts
[7 7 6 6 6]
counts
[5 5 5 4 4]
counts
[6 6 



 60%|█████▉    | 5981/9990 [00:03<00:01, 2110.46it/s]

 62%|██████▏   | 6204/9990 [00:03<00:01, 2132.72it/s]

counts
[7 6 6 6 6]
counts
[7 6 6 6 6]
counts
[7 6 6 6 6]
counts
[6 6 6 6 5]
counts
[6 6 6 5 5]
counts
[6 6 6 5 5]
counts
[6 6 6 6 6]
counts
[4 4 4 4 4]
counts
[6 5 5 5 5]
counts
[7 7 6 6 6]
counts
[7 7 6 6 6]
counts
[5 5 5 5 5]
counts
[6 6 5 5 5]
counts
[7 7 7 7 6]
counts
[8 8 7 7 7]
counts
[6 6 5 5 5]
counts
[6 6 6 6 5]
counts
[6 6 6 6 5]
counts
[7 7 7 6 6]
counts
[6 6 6 6 6]
counts
[4 4 4 3 3]
counts
[6 6 6 6 5]
counts
[5 5 4 4 4]
counts
[6 6 6 6 5]
counts
[6 6 6 6 5]
counts
[6 6 5 5 5]
counts
[4 4 4 4 3]
counts
[5 5 5 5 5]
counts
[7 7 6 6 6]
counts
[7 7 6 6 6]
counts
[5 5 5 4 4]
counts
[5 5 5 4 4]
counts
[6 6 5 5 5]
counts
[6 6 5 5 5]
counts
[6 6 6 6 6]
counts
[6 6 5 5 5]
counts
[7 6 6 6 6]
counts
[7 7 7 6 6]
counts
[5 5 4 4 4]
counts
[6 6 6 6 6]
counts
[7 7 7 7 7]
counts
[6 6 6 5 5]
counts
[6 6 6 6 5]
counts
[5 5 5 5 5]
counts
[5 4 4 4 4]
counts
[6 6 5 5 5]
counts
[6 6 6 6 5]
counts
[7 6 6 6 6]
counts
[7 6 6 6 6]
counts
[8 7 7 7 7]
counts
[6 6 5 5 5]
counts
[6 6 6 6 5]
counts
[6 6 



 64%|██████▍   | 6426/9990 [00:03<00:01, 2115.43it/s]

counts
[7 7 7 7 7]
counts
[6 6 6 5 5]
counts
[7 6 6 6 6]
counts
[6 6 6 6 6]
counts
[6 6 6 6 6]
counts
[7 7 7 7 7]
counts
[7 7 6 6 6]
counts
[7 6 6 6 6]
counts
[7 7 7 6 6]
counts
[5 5 5 5 5]
counts
[6 6 6 6 6]
counts
[7 7 7 6 6]
counts
[7 6 6 6 6]
counts
[8 7 7 7 7]
counts
[5 5 4 4 4]
counts
[8 7 7 7 7]
counts
[8 7 7 7 7]
counts
[6 6 6 5 5]
counts
[7 7 7 7 6]
counts
[7 7 6 6 6]
counts
[7 7 6 6 6]
counts
[6 6 6 6 6]
counts
[5 5 5 5 4]
counts
[7 7 7 7 6]
counts
[7 7 7 6 6]
counts
[6 6 6 6 6]
counts
[6 6 6 6 5]
counts
[8 8 8 8 7]
counts
[7 7 6 6 6]
counts
[7 7 7 7 7]
counts
[6 6 6 5 5]
counts
[7 7 6 6 6]
counts
[6 6 6 6 6]
counts
[7 7 7 6 6]
counts
[6 6 6 6 6]
counts
[8 7 7 7 7]
counts
[7 7 7 6 6]
counts
[7 7 7 7 6]
counts
[7 6 6 6 6]
counts
[7 6 6 6 6]
counts
[7 7 7 6 6]
counts
[7 7 7 7 6]
counts
[7 7 6 6 6]
counts
[7 6 6 6 6]
counts
[7 7 7 7 6]
counts
[7 6 6 6 6]
counts
[8 8 7 7 7]
counts
[7 7 6 6 6]
counts
[5 5 5 4 4]
counts
[7 7 7 6 6]
counts
[5 5 5 5 5]
counts
[7 6 6 6 6]
counts
[6 6 



 67%|██████▋   | 6644/9990 [00:03<00:01, 2029.46it/s]

 69%|██████▊   | 6852/9990 [00:03<00:01, 1991.80it/s]

counts
[8 8 7 7 7]
counts
[7 7 7 7 6]
counts
[8 7 7 7 7]
counts
[7 7 7 7 6]
counts
[8 7 7 7 7]
counts
[8 8 7 7 7]
counts
[7 7 6 6 6]
counts
[7 7 7 7 6]
counts
[6 6 6 6 6]
counts
[5 5 5 5 4]
counts
[7 6 6 6 6]
counts
[7 7 7 6 6]
counts
[6 6 6 6 6]
counts
[6 6 6 6 5]
counts
[11 11 11 11 11]
counts
[7 7 7 6 6]
counts
[8 8 8 7 7]
counts
[7 7 7 7 6]
counts
[8 8 7 7 7]
counts
[8 8 7 7 7]
counts
[7 7 7 7 6]
counts
[6 6 6 6 5]
counts
[6 6 6 5 5]
counts
[6 6 6 6 6]
counts
[7 7 7 7 6]
counts
[7 6 6 6 6]
counts
[7 7 7 7 7]
counts
[7 7 7 7 7]
counts
[8 8 8 8 8]
counts
[7 7 7 7 7]
counts
[8 8 8 8 7]
counts
[7 7 7 7 6]
counts
[7 7 7 6 6]
counts
[7 7 7 7 7]
counts
[8 7 7 7 7]
counts
[8 8 7 7 7]
counts
[7 6 6 6 6]
counts
[7 7 7 6 6]
counts
[9 9 8 8 8]
counts
[6 6 5 5 5]
counts
[8 7 7 7 7]
counts
[6 6 6 6 5]
counts
[7 7 7 6 6]
counts
[7 6 6 6 6]
counts
[7 7 7 7 7]
counts
[7 7 6 6 6]
counts
[6 6 6 6 5]
counts
[6 6 6 6 6]
counts
[6 6 6 6 6]
counts
[6 6 6 6 5]
counts
[7 7 7 6 6]
counts
[7 7 7 6 6]
counts




 71%|███████   | 7073/9990 [00:03<00:01, 2052.46it/s]

 73%|███████▎  | 7282/9990 [00:03<00:01, 1936.33it/s]

[9 9 8 8 8]
counts
[9 8 8 8 8]
counts
[8 8 7 7 7]
counts
[7 7 6 6 6]
counts
[6 6 6 6 5]
counts
[7 7 6 6 6]
counts
[9 9 9 8 8]
counts
[7 7 7 7 7]
counts
[8 8 8 8 7]
counts
[8 8 8 7 7]
counts
[8 8 7 7 7]
counts
[8 8 8 8 7]
counts
[8 8 8 7 7]
counts
[7 7 7 7 7]
counts
[9 9 9 9 8]
counts
[9 9 8 8 8]
counts
[8 8 8 8 7]
counts
[7 7 7 7 6]
counts
[8 8 8 8 7]
counts
[8 8 8 8 8]
counts
[9 9 9 9 9]
counts
[8 8 8 8 8]
counts
[7 7 6 6 6]
counts
[9 8 8 8 8]
counts
[8 8 8 8 7]
counts
[8 8 8 8 7]
counts
[7 6 6 6 6]
counts
[8 8 7 7 7]
counts
[7 7 7 7 6]
counts
[6 6 6 5 5]
counts
[9 8 8 8 8]
counts
[8 8 8 7 7]
counts
[8 8 8 8 7]
counts
[8 8 8 8 8]
counts
[8 8 8 8 7]
counts
[7 6 6 6 6]
counts
[8 8 8 8 8]
counts
[9 8 8 8 8]
counts
[8 8 7 7 7]
counts
[7 7 6 6 6]
counts
[8 7 7 7 7]
counts
[9 9 8 8 8]
counts
[7 6 6 6 6]
counts
[8 8 8 7 7]
counts
[7 7 7 6 6]
counts
[8 8 8 8 8]
counts
[9 9 9 9 8]
counts
[7 7 7 7 7]
counts
[8 8 8 7 7]
counts
[9 9 9 8 8]
counts
[8 8 8 7 7]
counts
[7 7 7 7 7]
counts
[8 8 8 7 7]




 75%|███████▍  | 7480/9990 [00:03<00:01, 1932.92it/s]

 77%|███████▋  | 7720/9990 [00:03<00:01, 2052.29it/s]

counts
[7 7 7 7 7]
counts
[8 8 8 7 7]
counts
[8 8 8 8 8]
counts
[8 7 7 7 7]
counts
[7 7 7 7 6]
counts
[9 9 9 8 8]
counts
[9 8 8 8 8]
counts
[7 7 7 7 7]
counts
[8 8 8 8 7]
counts
[9 8 8 8 8]
counts
[8 8 8 7 7]
counts
[8 8 8 8 7]
counts
[8 8 7 7 7]
counts
[7 7 7 6 6]
counts
[7 7 7 6 6]
counts
[9 9 8 8 8]
counts
[7 7 7 7 7]
counts
[7 7 7 7 6]
counts
[8 8 8 7 7]
counts
[7 7 7 7 7]
counts
[7 7 6 6 6]
counts
[7 7 7 7 6]
counts
[7 7 7 7 7]
counts
[13 13 13 13 12]
counts
[7 7 7 7 6]
counts
[9 8 8 8 8]
counts
[8 8 8 7 7]
counts
[8 8 8 8 7]
counts
[8 8 7 7 7]
counts
[8 8 7 7 7]
counts
[9 8 8 8 8]
counts
[9 8 8 8 8]
counts
[8 8 8 8 8]
counts
[8 8 8 7 7]
counts
[9 9 9 8 8]
counts
[7 7 7 6 6]
counts
[6 6 6 6 5]
counts
[10  9  9  9  9]
counts
[8 8 8 8 8]
counts
[6 6 5 5 5]
counts
[6 6 6 6 5]
counts
[8 8 8 8 7]
counts
[8 8 8 8 7]
counts
[8 8 8 8 7]
counts
[9 9 9 8 8]
counts
[8 8 8 8 7]
counts
[7 7 7 6 6]
counts
[8 8 8 8 7]
counts
[9 9 8 8 8]
counts
[8 8 8 8 7]
counts
[6 5 5 5 5]
counts
[7 7 7 7 6]
co



 79%|███████▉  | 7929/9990 [00:03<00:01, 1954.37it/s]

 82%|████████▏ | 8142/9990 [00:04<00:00, 2002.26it/s]

counts
[9 8 8 8 8]
counts
[8 8 8 8 7]
counts
[9 8 8 8 8]
counts
[10  9  9  9  9]
counts
[9 9 9 9 9]
counts
[9 9 8 8 8]
counts
[9 8 8 8 8]
counts
[9 9 9 9 8]
counts
[9 9 8 8 8]
counts
[9 8 8 8 8]
counts
[7 7 7 7 7]
counts
[6 6 6 6 6]
counts
[8 7 7 7 7]
counts
[8 8 7 7 7]
counts
[10  9  9  9  9]
counts
[8 7 7 7 7]
counts
[7 7 7 7 6]
counts
[8 8 8 8 8]
counts
[6 6 6 6 5]
counts
[9 9 9 8 8]
counts
[8 8 8 8 7]
counts
[7 7 7 6 6]
counts
[8 7 7 7 7]
counts
[7 7 7 7 7]
counts
[9 9 9 8 8]
counts
[9 9 8 8 8]
counts
[8 8 7 7 7]
counts
[6 6 6 6 6]
counts
[7 7 7 7 7]
counts
[9 8 8 8 8]
counts
[6 6 6 5 5]
counts
[8 8 8 7 7]
counts
[7 7 7 6 6]
counts
[10  9  9  9  9]
counts
[8 8 7 7 7]
counts
[8 8 8 7 7]
counts
[9 8 8 8 8]
counts
[9 8 8 8 8]
counts
[9 9 9 9 8]
counts
[9 9 8 8 8]
counts
[7 6 6 6 6]
counts
[8 8 7 7 7]
counts
[8 8 7 7 7]
counts
[8 7 7 7 7]
counts
[8 7 7 7 7]
counts
[9 9 9 8 8]
counts
[8 8 8 7 7]
counts
[7 7 7 7 7]
counts
[8 8 8 8 8]
counts
[6 6 6 6 6]
counts
[9 9 9 8 8]
counts
[8 8 8 8 



 84%|████████▎ | 8346/9990 [00:04<00:01, 1512.34it/s]

counts
[8 8 8 7 7]
counts
[8 8 8 8 7]
counts
[10 10  9  9  9]
counts
[9 9 9 9 8]
counts
[8 7 7 7 7]
counts
[9 8 8 8 8]
counts
[9 9 9 9 9]
counts
[8 8 8 7 7]
counts
[9 9 9 8 8]
counts
[10 10  9  9  9]
counts
[10 10 10  9  9]
counts
[9 9 9 9 9]
counts
[8 8 8 7 7]
counts
[9 9 8 8 8]
counts
[7 7 7 7 6]
counts
[7 7 7 7 7]
counts
[7 7 7 6 6]
counts
[7 7 7 7 7]
counts
[9 9 9 9 8]
counts
[9 9 9 8 8]
counts
[10 10  9  9  9]
counts
[10  9  9  9  9]
counts
[9 9 9 9 9]
counts
[7 7 7 7 7]
counts
[8 8 8 7 7]
counts
[9 9 9 9 8]
counts
[10  9  9  9  9]
counts
[9 9 9 9 9]
counts
[8 8 8 8 8]
counts
[7 6 6 6 6]
counts
[9 9 9 9 8]
counts
[9 8 8 8 8]
counts
[8 7 7 7 7]
counts
[8 8 8 8 7]
counts
[8 7 7 7 7]
counts
[9 9 9 8 8]
counts
[8 8 7 7 7]
counts
[10  9  9  9  9]
counts
[9 9 9 9 8]
counts
[10  9  9  9  9]
counts
[9 9 9 8 8]
counts
[9 9 8 8 8]
counts
[9 9 9 9 8]
counts
[6 6 5 5 5]
counts
[9 9 9 9 8]
counts
[8 8 8 8 8]
counts
[8 7 7 7 7]
counts
[10 10 10  9  9]
counts
[6 6 5 5 5]
counts
[9 9 8 8 8]
count



 86%|████████▌ | 8544/9990 [00:04<00:00, 1627.16it/s]

 88%|████████▊ | 8748/9990 [00:04<00:00, 1732.00it/s]


counts
[10  9  9  9  9]
counts
[8 8 8 8 8]
counts
[10  9  9  9  9]
counts
[10 10  9  9  9]
counts
[9 8 8 8 8]
counts
[8 7 7 7 7]
counts
[9 9 9 9 8]
counts
[8 8 8 8 8]
counts
[8 8 8 8 7]
counts
[9 9 9 9 8]
counts
[9 9 9 9 8]
counts
[9 9 9 8 8]
counts
[10  9  9  9  9]
counts
[10 10 10  9  9]
counts
[8 7 7 7 7]
counts
[8 8 8 8 7]
counts
[9 9 9 8 8]
counts
[9 9 9 9 9]
counts
[9 9 9 9 8]
counts
[10 10 10 10 10]
counts
[7 7 7 6 6]
counts
[7 7 7 7 6]
counts
[10 10 10  9  9]
counts
[8 8 8 8 8]
counts
[10 10 10  9  9]
counts
[9 9 9 9 8]
counts
[8 7 7 7 7]
counts
[9 8 8 8 8]
counts
[8 8 7 7 7]
counts
[8 8 8 8 8]
counts
[10 10 10  9  9]
counts
[10 10  9  9  9]
counts
[9 9 9 9 9]
counts
[9 8 8 8 8]
counts
[9 9 9 9 9]
counts
[10 10 10  9  9]
counts
[10 10 10  9  9]
counts
[8 8 8 8 8]
counts
[8 8 8 8 8]
counts
[10 10  9  9  9]
counts
[9 9 8 8 8]
counts
[10 10 10 10  9]
counts
[9 8 8 8 8]
counts
[10 10 10 10  9]
counts
[7 7 6 6 6]
counts
[9 8 8 8 8]
counts
[10 10  9  9  9]
counts
[10 10  9  9  9]
co



 90%|████████▉ | 8970/9990 [00:04<00:00, 1814.48it/s]

 92%|█████████▏| 9173/9990 [00:04<00:00, 1871.83it/s]

counts
[9 9 9 9 8]
counts
[7 7 7 7 7]
counts
[10 10 10  9  9]
counts
[8 8 8 7 7]
counts
[9 9 9 9 8]
counts
[9 9 9 9 9]
counts
[10 10 10 10  9]
counts
[8 8 8 8 8]
counts
[10 10 10 10  9]
counts
[7 7 6 6 6]
counts
[9 9 9 8 8]
counts
[9 9 9 9 9]
counts
[9 8 8 8 8]
counts
[11 11 10 10 10]
counts
[9 9 9 8 8]
counts
[9 9 9 8 8]
counts
[10 10 10 10  9]
counts
[9 9 9 8 8]
counts
[9 9 9 9 8]
counts
[10 10 10 10  9]
counts
[10 10 10 10  9]
counts
[9 9 8 8 8]
counts
[10 10  9  9  9]
counts
[8 8 8 8 7]
counts
[11 10 10 10 10]
counts
[8 8 8 8 8]
counts
[8 8 8 8 8]
counts
[9 9 8 8 8]
counts
[10 10 10  9  9]
counts
[9 8 8 8 8]
counts
[9 9 9 9 9]
counts
[8 8 8 8 7]
counts
[10 10 10 10  9]
counts
[9 9 8 8 8]
counts
[9 9 8 8 8]
counts
[11 10 10 10 10]
counts
[10 10  9  9  9]
counts
[11 11 11 10 10]
counts
[9 9 8 8 8]
counts
[10 10  9  9  9]
counts
[10 10  9  9  9]
counts
[9 9 8 8 8]
counts
[9 9 9 8 8]
counts
[9 9 9 9 8]
counts
[9 9 9 9 8]
counts
[10 10 10 10  9]
counts
[10 10 10  9  9]
counts
[10 10 10 



 94%|█████████▍| 9368/9990 [00:04<00:00, 1861.27it/s]

 96%|█████████▌| 9572/9990 [00:04<00:00, 1910.89it/s]

counts
[11 11 11 11 10]
counts
[10  9  9  9  9]
counts
[10 10  9  9  9]
counts
[10 10 10  9  9]
counts
[10 10 10 10 10]
counts
[10  9  9  9  9]
counts
[10 10  9  9  9]
counts
[8 7 7 7 7]
counts
[10  9  9  9  9]
counts
[10  9  9  9  9]
counts
[9 9 8 8 8]
counts
[9 8 8 8 8]
counts
[11 11 10 10 10]
counts
[9 9 8 8 8]
counts
[10 10  9  9  9]
counts
[10 10  9  9  9]
counts
[11 10 10 10 10]
counts
[10 10 10 10  9]
counts
[10 10  9  9  9]
counts
[9 9 9 9 8]
counts
[11 11 11 10 10]
counts
[10 10  9  9  9]
counts
[9 9 9 9 8]
counts
[10  9  9  9  9]
counts
[9 9 8 8 8]
counts
[10 10  9  9  9]
counts
[11 10 10 10 10]
counts
[10 10 10  9  9]
counts
[10 10 10 10 10]
counts
[11 11 11 11 10]
counts
[10 10 10 10 10]
counts
[10 10 10  9  9]
counts
[10 10 10  9  9]
counts
[11 11 11 10 10]
counts
[9 9 9 8 8]
counts
[11 11 11 11 10]
counts
[8 8 8 8 8]
counts
[11 11 10 10 10]
counts
[10 10 10 10 10]
counts
[9 9 9 9 9]
counts
[12 11 11 11 11]
counts
[9 9 9 9 8]
counts
[10 10 10 10 10]
counts
[10 10  9  9  9]



 98%|█████████▊| 9769/9990 [00:05<00:00, 1925.89it/s]

100%|█████████▉| 9965/9990 [00:05<00:00, 1922.76it/s]

counts
[10 10 10 10 10]
counts
[9 9 9 9 8]
counts
[10 10  9  9  9]
counts
[10 10  9  9  9]
counts
[11 10 10 10 10]
counts
[10  9  9  9  9]
counts
[12 12 11 11 11]
counts
[11 11 10 10 10]
counts
[9 9 9 9 8]
counts
[9 9 9 9 9]
counts
[10 10 10 10  9]
counts
[11 11 11 11 11]
counts
[8 8 8 7 7]
counts
[11 11 11 11 10]
counts
[11 10 10 10 10]
counts
[10 10 10 10  9]
counts
[10 10 10 10  9]
counts
[11 10 10 10 10]
counts
[11 11 11 10 10]
counts
[10  9  9  9  9]
counts
[11 11 11 10 10]
counts
[11 11 10 10 10]
counts
[10  9  9  9  9]
counts
[10  9  9  9  9]
counts
[7 7 7 7 7]
counts
[10 10 10 10  9]
counts
[10 10 10 10 10]
counts
[11 11 10 10 10]
counts
[11 11 11 11 11]
counts
[10  9  9  9  9]
counts
[11 11 10 10 10]
counts
[11 11 11 11 10]
counts
[11 10 10 10 10]
counts
[11 11 11 11 10]
counts
[10 10  9  9  9]
counts
[9 9 9 8 8]
counts
[9 9 8 8 8]
counts
[9 9 8 8 8]
counts
[10 10  9  9  9]
counts
[9 9 8 8 8]
counts
[11 11 11 11 10]
counts
[11 10 10 10 10]
counts
[11 10 10 10 10]
counts
[9 9 8

100%|██████████| 9990/9990 [00:05<00:00, 1791.74it/s]

df:
             img_file  bbox_x1  bbox_y1  bbox_x2  bbox_y2  class  fold
0     train_00001.jpg        1       80      641      461    108     0
1     train_00002.jpg       57       53      293      236     71     0
2     train_00003.jpg       35       42      227      160     76     0
3     train_00004.jpg       10       21      254      165    188     0
4     train_00005.jpg        1       67      772      573     44     0
...               ...      ...      ...      ...      ...    ...   ...
9985  train_09986.jpg       61      206      996      621    122     3
9986  train_09987.jpg      127       45      665      412    176     1
9987  train_09988.jpg       23       13      231      112    151     3
9988  train_09989.jpg       24      103      561      387     59     4
9989  train_09990.jpg       52      122      750      429     44     4

[9990 rows x 7 columns]
